### ISSUE TITLE
[bikeshed] Builds suddenly failing

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/spec#1993]
We have a build issue with Bikeshed again:
```
LINE 42:291 of status boilerplate: Found unmatched text macro [DEADLINE]. Correct the macro, or escape it by replacing the opening [ with &bs[;
LINE 48:290 of status boilerplate: Found unmatched text macro [DEADLINE]. Correct the macro, or escape it by replacing the opening [ with &bs[;
```
This error suddenly started appearing for [all three JS specs](https://github.com/WebAssembly/spec/actions/runs/18120405484).

@Ms2ger, can you please investigate?

**Comment by Ms2ger** [comment]
This seems like it might be consistent with being caused by https://github.com/speced/bikeshed-boilerplate/pull/173; cc @dschuff @tabatkins

**Comment by dschuff** [comment]
Yes, https://github.com/speced/bikeshed-boilerplate/pull/174 should have fixed it.

Edit: actually no nevermind, that's a different issue.

**Comment by tabatkins** [comment]
Ah, yeah, this sort of issue can happen due to the relative timing of macro processing vs includes/excludes. (Macros are done first, and aren't exclude-aware.) There's an easy fix, one sec.

**Comment by tabatkins** [comment]
Okay, fix pushed - I marked the two DEADLINE macros as allowed to silently fail. Deadline is already a required metadata for CRs, so it'll still be caught correctly there if you're missing it.

However, I note that the wasm boilerplate also uses the DEADLINE macro in its CRD paragraph, but Deadline isn't a required metadata for CRDs in general. Is it intentional to use DEADLINE there, or should y'all tweak your boilerplate a bit?

**Comment by dschuff** [comment]
Probably we should tweak the boilerplate. I'll look into that.

**Comment by dschuff** [comment]
Tab's fix upstream closes this bug. https://github.com/speced/bikeshed-boilerplate/pull/177 also removes use of the DEADLINE macro where it's not needed.

**Comment by rossberg** [comment]
Cool, thanks @tabatkins.

@dschuff, unrelated, but have you noticed that all our W3C pushes are still failing when trying to get the echidna result?

**Comment by dschuff** [comment]
yes, I have tried to fix that a couple of different times but haven't succeeded so far. I'll give it another shot today and maybe just remove the result check if I can't. better to have the blind push than having it fail all the time.

**Comment by dschuff** [comment]
#2000 fixes the problem for the js and web API specs.
