### ISSUE TITLE
[spec] Typo in prose for reduction rule for `table.set`: change `refs` to `elem`?

### ISSUE THREAD

**Issue by alessiofaieta** [WebAssembly/spec#2032]
In section "4 Execution > 4.6 Instructions > 4.6.7 Table Instructions > `table.set`", step 7 of the prose talks about replacing `z.tables[x].refs[i]`, but the formal notation uses `z.tables[x].elem[i]`, with `.elem` instead of `.refs`. I don't know if I'm missing something, but is this a typo? I think it should be `.elem` in both places, considering also that `.refs` is not a hyperlink.

The same thing happens for `elem.drop` in the same section, the prose uses `.refs` while the notation uses `.elem`.

**Comment by alessiofaieta** [comment]
I tried to briefly investigate this to try to fix it myself (assuming it is a typo), but I didn't manage to understand what to change, since I'm not familiar with the SpecTec infrastructure.

For example, the following line seems relevant, but both hints use `.REFS`:
https://github.com/WebAssembly/spec/blob/64478fce120760ffc006e4c992e21efd6b0154e7/specification/wasm-3.0/4.0-execution.configurations.spectec#L281

I'm not sure how some `.REFS` become `.elem`, if that is what's happening.

**Comment by rossberg** [comment]
Good catch. In fact, it should be .refs everywhere. The name mismatch problem was on the spec side, where a macro definition was outdated. Fixed in #2033.

The problem of the missing hyperlink in the prose lies a bit deeper, and has to do with the prose hints on the various $with_* functions. There is something missing in the expression that the prose backend generates from the hint, perhaps the right type info on the atom or missing macro context. @f52985, do you perhaps have an idea?

**Comment by alessiofaieta** [comment]
Got it, thank you :)

**Comment by alessiofaieta** [comment]
Would it be useful if I create a new issue for the problem of the missing hyperlink, since this issue is closed now? @rossberg

**Comment by rossberg** [comment]
Sure, please feel free to do so.

**Comment by alessiofaieta** [comment]
Okay, I just did, but in the meantime I also noticed that this issue is not completely resolved.

I mentioned that the instruction `elem.drop` had the same issue, but the fix didn't solve it. Moreover, I just noticed that it actually refers to `z.elems`, not `z.tables`, so I'm not sure that the same solution applies, i.e., I don't know if `.refs` in the prose needs to become `.elem`, or `.elem` in the formal notation needs to become `.refs`.

**Comment by alessiofaieta** [comment]
@rossberg I'm mentioning you because I don't know if you receive notifications for comments on closed issues, and I don't have permissions to reopen this issue (please see my previous comment). Sorry if this was not necessary.

**Comment by rossberg** [comment]
Ah, yes, thanks, I had missed one more macro. Should be fixed now (using refs), also in table.init.

(No worries, I get all notifications.)

**Comment by alessiofaieta** [comment]
Great! Thank you for the fast replies by the way :)
